apiVersion: v1
kind: Service
metadata:
  name: bharathi-nodeport-service
spec:
  type: NodePort
  selector:
    app: bharathi-app
  ports:
    - port: 80          
      targetPort: 80
      nodePort: 30000  